spring:
  application:
    name: market

  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  ai:
    openai:
      api-key: ${GROG_API}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.1-8b-instant
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      embedding:
        model: nomic-embed-text

#        m-pesa
mpesa:
  consumer-key: ${MPESA_CONSUMER_KEY:REPLACE_ME}
  consumer-secret: ${MPESA_CONSUMER_SECRET:REPLACE_ME}
  shortcode: ${MPESA_SHORTCODE:174379}
  passkey: ${MPESA_PASSKEY:REPLACE_ME}
  callback-url: ${MPESA_CALLBACK_URL:http://localhost:8080/api/v1/payments/webhook/mpesa}
  base-url: ${MPESA_BASE_URL:https://sandbox.safaricom.co.ke}